---
- hosts: all
  roles:
    - role: base
      tags: [base]

- name: Workstations
  hosts: workstation
  roles:
    - role: devenv
      tags: [devenv]
    - role: workstation
      tags: [workstation]
    - dotfiles

- hosts: wireguard
  roles:
    - wireguard

- name: DevEnv
  hosts: devenv
  roles:
    - role: devenv
      tags: [devenv]
    - dotfiles
