---

- name: Install common dev tools
  become: true
  dnf:
    state: present
    name: "{{ devenv_packages }}"
    update_cache: yes
  tags: [devenv]
 
- name: Set up gh-cli repository
  become: true
  copy:
    dest: /etc/yum.repos.d/gh-cli.repo
    content: |
      [gh-cli]
      name=packages for the GitHub CLI
      baseurl=https://cli.github.com/packages/rpm
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0
    mode: 0644
    owner: root
    group: root
  tags: [devenv, gh-cli]

- name: Install gh-cli
  become: true
  dnf:
    pkg: gh
  tags: [devenv, gh-cli] 
