---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Include workstation roles
  include_role:
    name: "{{ item }}"
    apply:
      tags:
        - install
        - "{{ item }}"
  loop:
    - dropbox
    - element
  tags: [install, dropbox, element]