---
- name: Install workstation snap packages
  become: true
  snap:
    state: present
    name:
      - firefox
      - spotify
      - zoom-client
  tags: [install]

- name: Install workstation snap packages with classic confinement
  become: true
  snap:
    state: present
    classic: yes
    name:
      - code
  tags: [install]