- name: Set up dropbox repository
  become: true
  apt_repository:
    repo: "deb [arch=i386,amd64] https://linux.dropbox.com/ubuntu disco main"
    filename: "dropbox"
    state: present
    update_cache: yes
  tags: [dropbox]

- name: Install dropbox
  become: true
  apt:
    pkg: dropbox
  tags: [dropbox]