---
- name: Install wireguard
  become: yes
  apt:
    name: wireguard
    state: present


- name: set wireguard server config
  become: yes
  template:
    src: wg_server.j2
    dest: '{{ (wireguard_path, wireguard_interface) | path_join }}.conf'
    owner: root
    group: root
    mode: '0600'
  when: "item.key == inventory_hostname"
  no_log: true
  with_dict: "{{ wireguard_server }}"
  notify: "restart wireguard service"

- name: start wireguard server and ensure it is enabled
  become: yes
  service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: started
    enabled: yes
  when: "item.key == inventory_hostname"
  no_log: true
  with_dict: "{{ wireguard_server }}"

- name: set wireguard client config
  become: yes
  template:
    src: wg_client.j2
    dest: '{{ (wireguard_path, wireguard_interface) | path_join }}.conf'
    owner: root
    group: root
    mode: '0600'
  when: "item.key == inventory_hostname"
  no_log: true
  with_dict: "{{ wireguard_peers }}"

